title: Grand Ole Time # The title of the blog
author: Parker Smith # Your name
email: grandma@psmith.dev # your email shown in the footer
url: https://www.grandoletime.com/ # this is your site's root address.
personal_url: https://psmith.dev/
description: A hand held tight, one generation to the next
favicon: "favicon.ico" # set the favicon of the site
show_excerpts: false # set to true to show excerpts on the homepage

# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "/assets/parker_clara.jpeg" # avatar in about page
  about_you: curious, empathetic, always learning. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter:
    github: psmithdev
    # rss: RSS
    # dribbble:
    facebook: psmitty50
    # flickr:
    # instagram:
    linkedin: parkersmith1
    # pinterest:
    # youtube:
    # youtube_channel:
    # youtube_channel_name:
    # telegram:
    # googleplus:
    # microdotblog:
    # reddit:
    email: grandma@psmith.dev

    # Mastodon instances
    # mastodon:
    # - username:
    #   instance:
    # - username:
    #   instance:

# Build settings
remote_theme: huangyz0918/moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
